### ISSUE TITLE
Failing when trying to run the: Example 1: Valuing Oracle's Common Equity, Based on 4 Quarters of History and 2 Quarters of Forecasts

### ISSUE THREAD

**Issue by mbkupfer** [jimlindstrom/FinModeling#12]
This is the message I get. 

```
Warning: failed to load entity
        wrong number of arguments (2 for 1)
        ["/myhomedirectory/.rvm/gems/ruby-2.1.1/gems/sec_query-1.1.0/lib/sec_query/entity.rb:37:in `find'"
         "/myhomedirectory/.rvm/gems/ruby-2.1.1/gems/finmodeling-0.2.1/lib/finmodeling/company.rb:44:in `find'"
         "./examples/show_reports.rb:119:in `<main>'"]
```

**Comment by jimlindstrom** [comment]
Hi @mbkupfer. I'm not actively supporting this project any more. If you are interested in taking it over, I'd be happy to help ramp you up. Or if you dig into this issue and have any suggestions, I would welcome a pull request.

**Comment by mbkupfer** [comment]
HI @jimlindstrom, while I'd like to take over such a project,  I'm still
just starting out with writing programs and don't think I'd have the
experience yet to take it over.
Especially since I'm still having issues just trying to understand how it
is all pieced together.

Maybe what would be great is if you could ramp me up with just the part
that pulls filing information into workable formats. Then I could take over
something more manageable. I did try looking into the gems you use in
Finmodeling but don't quite understand yet how you are connecting the xblr,
sec_query and the Edgar gem. To make matters more difficult, all the gems
seem to have little to no documentation.
